apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981368288270:role/eksctl-simple-jwt-api-cluster-nod-NodeInstanceRole-XVHSODV7JTU8
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-27T05:33:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1273"
  uid: a0e32a26-6988-4fee-a7f0-6f8dbb314ad0
